import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export async function generatePlagiarismPDF(result, originalText) {
  try {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    let yPosition = margin;

    // Helper function to add text with wrapping
    const addWrappedText = (text, fontSize, style = 'normal', y = yPosition) => {
      pdf.setFontSize(fontSize);
      pdf.setFont(undefined, style);
      const lines = pdf.splitTextToSize(text, pageWidth - margin * 2);
      pdf.text(lines, margin, y);
      return y + lines.length * (fontSize / 2.5);
    };

    // Title
    pdf.setFillColor(59, 130, 246); // blue color
    pdf.rect(0, 0, pageWidth, 30, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.setFont(undefined, 'bold');
    pdf.text('Plagiarism Report', pageWidth / 2, 20, { align: 'center' });
    
    // Reset text color
    pdf.setTextColor(0, 0, 0);
    yPosition = 40;

    // Generation date
    pdf.setFontSize(10);
    pdf.setFont(undefined, 'normal');
    pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, yPosition);
    yPosition += 10;

    // Overall Scores Section
    pdf.setFontSize(14);
    pdf.setFont(undefined, 'bold');
    yPosition = addWrappedText('Overall Scores', 14, 'bold', yPosition);
    yPosition += 5;

    pdf.setFontSize(11);
    pdf.setFont(undefined, 'normal');
    pdf.setTextColor(220, 38, 38); // red for plagiarism score
    yPosition = addWrappedText(`Plagiarism Percentage: ${result.plagiarismPercentage}%`, 11, 'bold', yPosition);
    
    pdf.setTextColor(0, 0, 0);
    yPosition = addWrappedText(`Similarity Score: ${result.overallScore}%`, 11, 'normal', yPosition);
    yPosition += 8;

    // Analysis Stats
    pdf.setFontSize(14);
    pdf.setFont(undefined, 'bold');
    pdf.setTextColor(0, 0, 0);
    yPosition = addWrappedText('Analysis Statistics', 14, 'bold', yPosition);
    yPosition += 5;

    pdf.setFontSize(11);
    pdf.setFont(undefined, 'normal');
    const statsText = [
      `Total Sentences Analyzed: ${result.totalSentences}`,
      `Plagiarized Sentences: ${result.plagiarizedSentences}`,
      `Original Sentences: ${result.totalSentences - result.plagiarizedSentences}`,
      `Plagiarism Rate: ${((result.plagiarizedSentences / result.totalSentences) * 100).toFixed(2)}%`
    ];

    statsText.forEach(stat => {
      yPosition = addWrappedText(stat, 10, 'normal', yPosition);
    });
    yPosition += 8;

    // Detailed Results Section
    pdf.setFontSize(14);
    pdf.setFont(undefined, 'bold');
    yPosition = addWrappedText('Detailed Sentence Analysis', 14, 'bold', yPosition);
    yPosition += 8;

    // Results table
    result.results.forEach((item, index) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 40) {
        pdf.addPage();
        yPosition = margin;
      }

      // Sentence with status
      pdf.setFontSize(10);
      pdf.setFont(undefined, item.isPlagiarized ? 'bold' : 'normal');
      pdf.setTextColor(item.isPlagiarized ? 220 : 34, item.isPlagiarized ? 38 : 197, 34);
      
      const status = item.isPlagiarized ? '❌ PLAGIARIZED' : '✓ ORIGINAL';
      yPosition = addWrappedText(`${index + 1}. [${status}] (${item.similarity}%)`, 9, 'bold', yPosition);
      
      // Sentence text
      pdf.setFontSize(9);
      pdf.setFont(undefined, 'normal');
      pdf.setTextColor(0, 0, 0);
      const sentenceLines = pdf.splitTextToSize(`"${item.sentence}"`, pageWidth - margin * 2 - 4);
      pdf.text(sentenceLines, margin + 2, yPosition);
      yPosition += sentenceLines.length * 4 + 2;

      // Sources
      if (item.sources.length > 0) {
        pdf.setFontSize(8);
        pdf.setFont(undefined, 'bold');
        yPosition = addWrappedText('Sources:', 8, 'bold', yPosition);
        
        item.sources.forEach((source, idx) => {
          pdf.setFontSize(8);
          pdf.setFont(undefined, 'normal');
          pdf.setTextColor(59, 130, 246);
          const sourceText = `${idx + 1}. ${source.url} (${source.similarity}% match)`;
          const sourceLines = pdf.splitTextToSize(sourceText, pageWidth - margin * 2 - 8);
          pdf.text(sourceLines, margin + 4, yPosition);
          yPosition += sourceLines.length * 3.5;
        });
      }

      yPosition += 3;
      pdf.setTextColor(0, 0, 0);
    });

    // Footer
    yPosition += 10;
    pdf.setFontSize(8);
    pdf.setFont(undefined, 'normal');
    pdf.setTextColor(128, 128, 128);
    pdf.text('This report was generated by the Free Plagiarism Checker', pageWidth / 2, pageHeight - 10, { align: 'center' });

    // Save PDF
    const fileName = `plagiarism-report-${new Date().getTime()}.pdf`;
    pdf.save(fileName);
    
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
}
